version: '3.8'

services:
  db:
    container_name: db
    hostname: "relational-database"
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "8091:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 196218
      MYSQL_DATABASE: api
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    networks:
      - spring-cloud-network

  api:
    container_name: api-spring
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge
